// 6-sinf O'zbekiston darsliklari asosidagi 11 ta fan bo'yicha 15 talik test savollari banki
export const QUESTION_BANK_GRADE_6 = {
  "Matematika": [
    { text: "24 va 36 sonlarining eng katta umumiy bo'luvchisini (EKUB) toping.", options: ["6", "12", "18", "24"], correctIndex: 1 },
    { text: "12 va 15 sonlarining eng kichik umumiy karralisini (EKUK) toping.", options: ["30", "60", "90", "120"], correctIndex: 1 },
    { text: "3/4 kasrni o'nli kasr ko'rinishida yozing.", options: ["0.25", "0.5", "0.75", "0.8"], correctIndex: 2 },
    { text: "Kvadratning tomoni 6 sm bo'lsa, uning yuzini toping.", options: ["24 sm²", "36 sm²", "12 sm²", "30 sm²"], correctIndex: 1 },
    { text: "To'g'ri to'rtburchakning bo'yi 8 sm, eni 5 sm. Uning perimetrini toping.", options: ["13 sm", "26 sm", "40 sm", "20 sm"], correctIndex: 1 },
    { text: "-7 + (-5) ifodaning qiymatini hisoblang.", options: ["-12", "12", "-2", "2"], correctIndex: 0 },
    { text: "(-8) · (-4) ko'paytmani hisoblang.", options: ["-32", "32", "-12", "12"], correctIndex: 1 },
    { text: "Proporsiyaning noma'lum hadini toping: x : 4 = 15 : 6", options: ["10", "8", "12", "6"], correctIndex: 0 },
    { text: "Sonning 20% i 40 ga teng bo'lsa, shu sonning o'zini toping.", options: ["100", "200", "80", "150"], correctIndex: 1 },
    { text: "0.25 sonini oddiy kasr ko'rinishida yozing.", options: ["1/2", "1/4", "1/5", "2/5"], correctIndex: 1 },
    { text: "Doiraning radiusi 5 sm bo'lsa, uning diametrini toping.", options: ["10 sm", "15 sm", "25 sm", "20 sm"], correctIndex: 0 },
    { text: "Uchburchakning ichki burchaklari yig'indisi necha gradusga teng?", options: ["90°", "180°", "360°", "270°"], correctIndex: 1 },
    { text: "Tenglamani yeching: 3x + 7 = 22", options: ["3", "5", "6", "7"], correctIndex: 1 },
    { text: "7/9 va 5/9 kasrlarining yig'indisini toping.", options: ["12/18", "12/9", "2/9", "35/81"], correctIndex: 1 },
    { text: "Koordinatalar to'g'ri chizig'ida 0 dan chapda qanday sonlar joylashadi?", options: ["Musbat", "Manfiy", "Kasr", "Tub"], correctIndex: 1 }
  ],

  "Ona tili": [
    { text: "Qo'shimchalar vazifasiga ko'ra necha turga bo'linadi?", options: ["2 turga", "3 turga", "4 turga", "5 turga"], correctIndex: 0 },
    { text: "So'z yasovchi qo'shimcha qatnashgan so'zni toping.", options: ["Kitoblar", "Gulzor", "Uydan", "Maktabga"], correctIndex: 1 },
    { text: "Qaratqich kelishigining qo'shimchasi qaysi?", options: ["-ni", "-ning", "-ga", "-da"], correctIndex: 1 },
    { text: "Tushum kelishigi qaysi so'roqlarga javob bo'ladi?", options: ["Kimni? Nimani?", "Kimga? Nimaga?", "Kimda? Nimada?", "Kimdan? Nimadan?"], correctIndex: 0 },
    { text: "Otning egalik qo'shimchalari nechta shaxsga ega?", options: ["2 ta", "3 ta", "4 ta", "6 ta"], correctIndex: 1 },
    { text: "Sifat darajalari nechta?", options: ["2 ta", "3 ta", "4 ta", "5 ta"], correctIndex: 2 },
    { text: "Orttirma darajadagi sifatni toping.", options: ["Qizil", "Qip-qizil", "Qizg'ish", "Oqroq"], correctIndex: 1 },
    { text: "Dona sonni ko'rsatuvchi qo'shimchani toping.", options: ["-ta", "-tacha", "-tadan", "-ovlon"], correctIndex: 0 },
    { text: "Olmoshning ma'no jihatdan necha turi bor?", options: ["5 ta", "6 ta", "7 ta", "8 ta"], correctIndex: 2 },
    { text: "Kishilik olmoshlarini toping.", options: ["Men, sen, u", "Bu, shu, o'sha", "Kim, nima", "Hamma, barcha"], correctIndex: 0 },
    { text: "Fe'lning bo'lishsiz shakli qaysi qo'shimcha bilan yasaladi?", options: ["-ma", "-siz", "-chi", "-moq"], correctIndex: 0 },
    { text: "Ko'makchilar qaysi so'z turkumi guruhiga kiradi?", options: ["Mustaqil", "Yordamchi", "Alohida", "Undov"], correctIndex: 1 },
    { text: "Uyushiq bo'laklar orasiga qanday tinish belgisi qo'yiladi?", options: ["Vergul", "Nuqta", "Tire", "Qavs"], correctIndex: 0 },
    { text: "Ega va kesim qanday bo'laklar hisoblanadi?", options: ["Bosh bo'laklar", "Ikkinchi darajali", "Undalma", "Kirish so'z"], correctIndex: 0 },
    { text: "O'zbek tilida nechta kelishik bor?", options: ["4 ta", "5 ta", "6 ta", "7 ta"], correctIndex: 2 }
  ],

  "Adabiyot": [
    { text: "Alpomish dostonida Barchinoyning otasi kim?", options: ["Boybo'ri", "Boysari", "Qorajon", "Yodgor"], correctIndex: 1 },
    { text: "\"Alpomish\" dostonida Alpomishning tulpori nomi nima?", options: ["Boychibor", "G'irot", "Qirko'k", "Jeyron"], correctIndex: 0 },
    { text: "Zahiriddin Muhammad Bobur qayerda tavallud topgan?", options: ["Samarqand", "Andijon", "Hirot", "Qobul"], correctIndex: 1 },
    { text: "Boburning mashhur tarixiy va adabiy asari qaysi?", options: ["Boburnoma", "Xamsa", "Devonu lug'otit turk", "Qutadg'u bilig"], correctIndex: 0 },
    { text: "G'afur G'ulomning bolalarga bag'ishlangan mashhur qissasi qaysi?", options: ["Shum bola", "O'tkan kunlar", "Sariq devni minib", "Yulduzli tunlar"], correctIndex: 0 },
    { text: "\"Shum bola\" asaridagi bosh qahramonning ismi nima?", options: ["Qoravoy", "Omon", "Hoshimjon", "Yodgor"], correctIndex: 0 },
    { text: "Xudoyberdi To'xtaboyevning ertak-qissasi qaysi?", options: ["Sariq devni minib", "Shum bola", "Dunyoning ishlari", "Oq kema"], correctIndex: 0 },
    { text: "\"Sariq devni minib\" asaridagi sehrli shapkacha egasi kim?", options: ["Hoshimjon", "Qoravoy", "Akrom", "Doniyor"], correctIndex: 0 },
    { text: "Erkin Vohidov qalamiga mansub dostonni toping.", options: ["Nido", "Ruhlar isyoni", "Surat bilan suhbat", "Ona tili"], correctIndex: 0 },
    { text: "Abdulla Oripov O'zbekiston Respublikasining qaysi ramzi matni muallifi?", options: ["Davlat Madhiyasi", "Gerb", "Bayroq", "Konstitutsiya"], correctIndex: 0 },
    { text: "Ruboiy necha misradan iborat bo'ladi?", options: ["2 misra", "4 misra", "6 misra", "8 misra"], correctIndex: 1 },
    { text: "Masal janrining asosiy xususiyati nima?", options: ["Kinoyaviy va pand-nasihat ruhida bo'lishi", "Tarixiy voqelik", "Faqat nasriy bo'lishi", "Qahramonlik"], correctIndex: 0 },
    { text: "Maqol va matalning asosiy farqi nimada?", options: ["Maqolda tugal fikr bo'ladi", "Matal uzun bo'ladi", "Farqi yo'q", "Maqol faqat she'riy bo'ladi"], correctIndex: 0 },
    { text: "Ertaklar mavzusiga ko'ra nechta turga bo'linadi?", options: ["2 ta", "3 ta", "4 ta", "5 ta"], correctIndex: 1 },
    { text: "Alisher Navoiy qaysi asari bilan turkiy tilda \"Xamsa\" yaratgan?", options: ["Xamsa", "Lison ut-tayr", "Majolis un-nafois", "Mahbub ul-qulub"], correctIndex: 0 }
  ],

  "Tarix": [
    { text: "Eng qadimgi odamlarning qoldiqlari topilgan Teshiktosh g'ori qayerda joylashgan?", options: ["Surxondaryoda", "Qashqadaryoda", "Farg'onada", "Toshkentda"], correctIndex: 0 },
    { text: "Qadimgi Misr davlati qaysi daryo bo'yida vujudga kelgan?", options: ["Nil", "Dajla", "Furot", "Hind"], correctIndex: 0 },
    { text: "Mesopotamiya qaysi ikki daryo oralig'ida joylashgan?", options: ["Dajla va Furot", "Amudaryo va Sirdaryo", "Nil va Kongo", "Hind va Gang"], correctIndex: 0 },
    { text: "Qadimgi Bobil podshosi Xammurappi nima bilan mashhur bo'lgan?", options: ["Qonunlar to'plami bilan", "Piramidalar qurgani bilan", "Dengiz sayohati bilan", "Kutubxona ochgani bilan"], correctIndex: 0 },
    { text: "Zardushtiylik dinining muqaddas kitobi nima deb ataladi?", options: ["Avesto", "Veda", "Injil", "Qur'on"], correctIndex: 0 },
    { text: "Avestoda ezgulik xudosi qanday nomlangan?", options: ["Axuramazda", "Axriman", "Mitra", "Anaxita"], correctIndex: 0 },
    { text: "Qadimgi Xitoyda Buyuk Ipak Yo'li orqali asosan nima tashilgan?", options: ["Ipak va choy", "Neft", "Paxta", "Bug'doy"], correctIndex: 0 },
    { text: "Buyuk Xitoy devori nima maqsadda qurilgan?", options: ["Ko'chmanchilar hujumidan himoyalanish uchun", "Savdo qilish uchun", "Chegarani belgilash uchun", "Sayyohlar uchun"], correctIndex: 0 },
    { text: "Qadimgi Hindistonda qanday yozuv vujudga kelgan?", options: ["Sanskrit (Braxmi)", "Mixxat", "Iyeroglif", "Lotin"], correctIndex: 0 },
    { text: "Qadimgi Yunonistonda Olimpiya o'yinlari necha yilda bir marta o'tkazilgan?", options: ["2 yilda", "3 yilda", "4 yilda", "5 yilda"], correctIndex: 2 },
    { text: "Aleksandr Makedonskiyning ustozi mashhur yunon olimi kim?", options: ["Arastu (Aristotel)", "Aflotun (Platon)", "Suqrot (Sokrat)", "Pifagor"], correctIndex: 0 },
    { text: "Qadimgi Rimda davlatni boshqargan saylanadigan oliy mansabdorlar kimlar?", options: ["Konsullar", "Senatorlar", "Imperatorlar", "Tribunlar"], correctIndex: 0 },
    { text: "Qadimgi Baqtriya davlatining poytaxti qaysi shahar bo'lgan?", options: ["Baqtra (Zariaspa)", "Marokand", "Kesh", "Termiz"], correctIndex: 0 },
    { text: "Spitamen kimlarga qarshi kurashgan milliy qahramon?", options: ["Makedoniyalik Iskandarga", "Eron shohi Kir II ga", "Arab bosqinchilariga", "Rimliklarga"], correctIndex: 0 },
    { text: "Qadimgi So'g'diyona davlatining markazi qaysi shahar bo'lgan?", options: ["Marokand (Samarqand)", "Buxoro", "Xiva", "Chach"], correctIndex: 0 }
  ],

  "Ingliz tili": [
    { text: "Choose the correct pronoun: \"... is my best friend. Her name is Mary.\"", options: ["He", "She", "It", "They"], correctIndex: 1 },
    { text: "What is the plural form of \"child\"?", options: ["Childs", "Children", "Childrens", "Childes"], correctIndex: 1 },
    { text: "Choose the correct form: \"They ... playing football now.\"", options: ["is", "am", "are", "was"], correctIndex: 2 },
    { text: "What is the opposite of \"hot\"?", options: ["Warm", "Cold", "Dry", "Wet"], correctIndex: 1 },
    { text: "Choose the correct preposition: \"I get up ... 7 o'clock.\"", options: ["on", "at", "in", "to"], correctIndex: 1 },
    { text: "Which sentence is in the Past Simple tense?", options: ["I went to school yesterday", "I go to school", "I am going to school", "I will go to school"], correctIndex: 0 },
    { text: "Choose the correct word: \"She ... a red bag.\"", options: ["have", "has", "is", "are"], correctIndex: 1 },
    { text: "What day comes after Tuesday?", options: ["Monday", "Wednesday", "Thursday", "Friday"], correctIndex: 1 },
    { text: "Comparative form of \"big\":", options: ["Bigger", "More big", "Biggest", "Bigest"], correctIndex: 0 },
    { text: "How many months are there in a year?", options: ["10", "11", "12", "14"], correctIndex: 2 },
    { text: "Choose the correct article: \"She has ... apple.\"", options: ["a", "an", "the", "-"], correctIndex: 1 },
    { text: "What is the third person singular of \"watch\"?", options: ["Watchs", "Watches", "Watching", "Watched"], correctIndex: 1 },
    { text: "\"We ... students.\"", options: ["is", "are", "am", "be"], correctIndex: 1 },
    { text: "Which word is an adjective?", options: ["Quickly", "Beautiful", "Run", "Book"], correctIndex: 1 },
    { text: "Choose the correct question word: \"... are you from? - I am from Uzbekistan.\"", options: ["When", "Where", "Why", "Who"], correctIndex: 1 }
  ],

  "Informatika": [
    { text: "Axborotning eng kichik o'lchov birligi nima?", options: ["Bayt", "Bit", "Kilobayt", "Megabayt"], correctIndex: 1 },
    { text: "1 Bayt necha bitga teng?", options: ["4 bit", "8 bit", "16 bit", "1024 bit"], correctIndex: 1 },
    { text: "1 Kilobayt (KB) necha baytga teng?", options: ["1000 bayt", "1024 bayt", "512 bayt", "2048 bayt"], correctIndex: 1 },
    { text: "Kompyuterning miyasi hisoblangan asosiy mikrosxema nima?", options: ["Protsessor (CPU)", "Vinchester", "Monitor", "Printer"], correctIndex: 0 },
    { text: "Matn kiritish uchun xizmat qiluvchi asosiy qurilma qaysi?", options: ["Klaviatura", "Sichqoncha", "Kalonka", "Skaner"], correctIndex: 0 },
    { text: "Axborotni ekranda aks ettiruvchi qurilma nima?", options: ["Monitor", "Printer", "Modem", "Mikrofon"], correctIndex: 0 },
    { text: "Quyidagilardan qaysi biri operatsion sistema hisoblanadi?", options: ["Windows", "Word", "Excel", "Paint"], correctIndex: 0 },
    { text: "Fayl nomi va uning kengaytmasi o'rtasiga qanday belgi qo'yiladi?", options: ["Nuqta (.)", "Vergul (,)", "Tire (-)", "Yulduzcha (*)"], correctIndex: 0 },
    { text: "Grafik fayl kengaytmasini toping.", options: [".jpg / .png", ".txt / .docx", ".mp3", ".exe"], correctIndex: 0 },
    { text: "Kursorning chap tomonidagi belgini o'chiruvchi tugma qaysi?", options: ["Backspace", "Delete", "Enter", "Shift"], correctIndex: 0 },
    { text: "Bosh harflar bilan yozish rejimini yoquvchi tugma qaysi?", options: ["Caps Lock", "Alt", "Ctrl", "Tab"], correctIndex: 0 },
    { text: "Fayl va papkalarni nusxalashning tezkor tugmasi qaysi?", options: ["Ctrl + C", "Ctrl + V", "Ctrl + Z", "Ctrl + X"], correctIndex: 0 },
    { text: "Nusxalangan obyektni qo'yish (joylashtirish) tezkor tugmasi qaysi?", options: ["Ctrl + V", "Ctrl + C", "Ctrl + A", "Ctrl + S"], correctIndex: 0 },
    { text: "Butun dunyo bo'ylab kompyuterlarni bog'lovchi global tarmoq nima?", options: ["Internet", "LAN", "Bluetooth", "Wi-Fi"], correctIndex: 0 },
    { text: "Matn tahrirlovchi mashhur dastur qaysi?", options: ["Microsoft Word", "Paint", "Photoshop", "Kalkulyator"], correctIndex: 0 }
  ],

  "Geografiya": [
    { text: "Yer sharining eng kichik qisqartirilgan modeli nima?", options: ["Globus", "Xarita", "Plan", "Atlas"], correctIndex: 0 },
    { text: "Yer yuzida nechta materik mavjud?", options: ["5 ta", "6 ta", "7 ta", "4 ta"], correctIndex: 1 },
    { text: "Eng katta materik qaysi?", options: ["Yevrosiyo", "Afrika", "Shimoliy Amerika", "Antarktida"], correctIndex: 0 },
    { text: "Eng kichik materik qaysi?", options: ["Avstraliya", "Janubiy Amerika", "Antarktida", "Yevropa"], correctIndex: 0 },
    { text: "Yer sharida nechta okean bor?", options: ["3 ta", "4 ta", "5 ta", "6 ta"], correctIndex: 1 },
    { text: "Eng katta va eng chuqur okean qaysi?", options: ["Tinch okeani", "Atlantika okeani", "Hind okeani", "Shimoliy Muz okeani"], correctIndex: 0 },
    { text: "Dunyo okeanining eng chuqur joyi qaysi?", options: ["Mariana botig'i", "Yava botig'i", "Baykal", "Orol"], correctIndex: 0 },
    { text: "Ekvator chizig'i Yer sharini qanday ikkita yarim sharga bo'ladi?", options: ["Shimoliy va Janubiy", "Sharqiy va G'arbiy", "Markaziy va Chekka", "Qutbiy"], correctIndex: 0 },
    { text: "Dunyoning eng baland cho'qqisi qaysi?", options: ["Jomolungma (Everest)", "Monblan", "Elbrus", "G'alaba cho'qqisi"], correctIndex: 0 },
    { text: "Dunyodagi eng uzun daryo qaysi?", options: ["Nil (yoki Amazonka)", "Volga", "Yanszi", "Missisipi"], correctIndex: 0 },
    { text: "Yer yuzidagi eng chuqur chuchuk suvli ko'l qaysi?", options: ["Baykal", "Kaspiy", "Viktoriya", "Ladoga"], correctIndex: 0 },
    { text: "Kompasning ko'k ko'rsatkichi qaysi tomonni ko'rsatadi?", options: ["Shimolni", "Janubni", "Sharqni", "G'arbni"], correctIndex: 0 },
    { text: "O'zbekiston qaysi materikda joylashgan?", options: ["Yevrosiyo", "Afrika", "Amerika", "Avstraliya"], correctIndex: 0 },
    { text: "Atmosferaning Yer yuzasiga eng yaqin quyi qatlami nima deb ataladi?", options: ["Troposfera", "Stratosfera", "Mezosfera", "Termosfera"], correctIndex: 0 },
    { text: "Havo harorati qanday asbob yordamida o'lchanadi?", options: ["Termometr", "Barometr", "Gigrometr", "Anemometr"], correctIndex: 0 }
  ],

  "Botanika": [
    { text: "Botanika nimani o'rganadigan fan?", options: ["O'simliklarni", "Hayvonlarni", "Qushlarni", "Toshlarni"], correctIndex: 0 },
    { text: "O'simlik hujayrasini kattalashtirib ko'rsatuvchi asbob nima?", options: ["Mikroskop", "Teleskop", "Binokl", "Termometr"], correctIndex: 0 },
    { text: "O'simlikka yashil rang beruvchi pigment nima?", options: ["Xlorofill", "Karotin", "Antotsian", "Glyukoza"], correctIndex: 0 },
    { text: "Fotosintez jarayonida o'simlik qanday gazni yutadi?", options: ["Karbonat angidrid", "Kislorod", "Azot", "Vodorod"], correctIndex: 0 },
    { text: "Fotosintez natijasida o'simlikdan qanday gaz ajralib chiqadi?", options: ["Kislorod", "Karbonat angidrid", "Geliy", "Metan"], correctIndex: 0 },
    { text: "O'simlikning asosiy vegetativ organlarini ko'rsating.", options: ["Ildiz, poya, barg", "Gul, meva, urug'", "Faqat gul", "Faqat meva"], correctIndex: 0 },
    { text: "Ildizning asosiy vazifasi nima?", options: ["Tuproqdan suv va mineral moddalarni shimish", "Fotosintez qilish", "Changlanish", "Meva hosil qilish"], correctIndex: 0 },
    { text: "Ildiz tizimi qanday turlarga bo'linadi?", options: ["O'qildiz va popukildiz", "Uzun va kalta", "To'g'ri va qiyshiq", "Bosh va yon"], correctIndex: 0 },
    { text: "Bargning gaz almashinuvi va suv bug'latishiga xizmat qiluvchi qismi nima?", options: ["Og'izchalar (ustitsa)", "Et qismi", "Tomirlar", "Barg bandi"], correctIndex: 0 },
    { text: "Gulli o'simliklarning generativ organi nima?", options: ["Gul", "Poya", "Barg", "Ildiz"], correctIndex: 0 },
    { text: "Gulning asosiy ko'payish qismlari qaysilar?", options: ["Changchi va urug'chi", "Gultojibarg va kosachabarg", "Gulband va gulo'rni", "Faqat gultojibarg"], correctIndex: 0 },
    { text: "Changchi boshchasida nima yetiladi?", options: ["Chang donachalari", "Urug'kurtak", "Meva", "Nektar"], correctIndex: 0 },
    { text: "Bir yillik madaniy o'simlikni toping.", options: ["Bug'doy", "Olma", "Yong'oq", "Terak"], correctIndex: 0 },
    { text: "Ko'p yillik daraxt shaklidagi o'simlik qaysi?", options: ["Eman (Dub)", "Pomidor", "Makkajo'xori", "Qovun"], correctIndex: 0 },
    { text: "Tuban o'simliklarga qaysi biri kiradi?", options: ["Suvo'tlar", "Qirqquloqlar", "Ochiq urug'lilar", "Yopiq urug'lilar"], correctIndex: 0 }
  ],

  "Fizika": [
    { text: "Tabiat hodisalarini o'rganuvchi asosiy fan nima?", options: ["Fizika", "Adabiyot", "Tarix", "Huquq"], correctIndex: 0 },
    { text: "Xalqaro birliklar sistemasida (SI) uzunlik birligi nima?", options: ["Metr", "Kilometr", "Santimetr", "Millimetr"], correctIndex: 0 },
    { text: "SI sistemasida vaqt birligi nima?", options: ["Sekund", "Minut", "Soat", "Sutka"], correctIndex: 0 },
    { text: "SI sistemasida massa birligi nima?", options: ["Kilogramm", "Gramm", "Tonna", "Sentner"], correctIndex: 0 },
    { text: "Tezlikni hisoblash formulasi qaysi?", options: ["v = s / t", "s = v · t", "t = s / v", "F = m · a"], correctIndex: 0 },
    { text: "Jismning massasi qanday asbob yordamida o'lchanadi?", options: ["Tarozi", "Lineyka", "Sekundomer", "Termometr"], correctIndex: 0 },
    { text: "Moddaning nechta asosiy agregat holati bor?", options: ["3 ta (qattiq, suyuq, gaz)", "2 ta", "4 ta", "5 ta"], correctIndex: 0 },
    { text: "Kuch birligi qaysi olim nomi bilan ataladi?", options: ["Nyuton (N)", "Paskal (Pa)", "Joul (J)", "Vatt (W)"], correctIndex: 0 },
    { text: "Bosim birligi nima?", options: ["Paskal (Pa)", "Nyuton", "Amper", "Volt"], correctIndex: 0 },
    { text: "Barcha jismlar Yerga tortilishini ifodalovchi kuch nima?", options: ["Og'irlik kuchi", "Ishqalanish kuchi", "Elastiklik kuchi", "Arximed kuchi"], correctIndex: 0 },
    { text: "Molekula nimalardan tashkil topgan?", options: ["Atomlardan", "Hujayralardan", "Elektronlardan", "Tomchilardan"], correctIndex: 0 },
    { text: "Haroratni o'lchash birligi nima?", options: ["Selsiy gradusi (°C)", "Joul", "Kilogramm", "Paskal"], correctIndex: 0 },
    { text: "Yorug'likning vakuumdagi tezligi sekundiga taxminan qancha?", options: ["300 000 km/s", "150 000 km/s", "1 000 km/s", "30 000 km/s"], correctIndex: 0 },
    { text: "Quyosh atrofida aylanuvchi eng yaqin sayyora qaysi?", options: ["Merkuriy", "Venera", "Mars", "Yupiter"], correctIndex: 0 },
    { text: "Suyuqlik va gazlarda bosim barcha yo'nalishlarda bir xil uzatilishini qaysi qonun tushuntiradi?", options: ["Paskal qonuni", "Arximed qonuni", "Nyuton qonuni", "Om qonuni"], correctIndex: 0 }
  ],

  "Texnologiya": [
    { text: "Yog'ochga ishlov berishda qo'llaniladigan asosiy kesish quroli nima?", options: ["Arra", "Bolg'a", "Randa", "Ombir"], correctIndex: 0 },
    { text: "Yog'och sirtini tekislash va silliqlash uchun qaysi asbob ishlatiladi?", options: ["Randa", "Arra", "Drel", "Qisqich"], correctIndex: 0 },
    { text: "Metallarni kesish uchun qanday arra ishlatiladi?", options: ["Temir arra (chilangarlik arrasi)", "Daraxt arrasi", "Lobzik", "Pichoq"], correctIndex: 0 },
    { text: "Chilangarlik dastgohida detalni mahkamlab turuvchi moslama nima?", options: ["Tiski (morza)", "Bolg'a", "Randa", "Zubilo"], correctIndex: 0 },
    { text: "O'lchov ishlarida yuqori aniqlikda o'lchaydigan asbob qaysi?", options: ["Shtangensirkul", "Chizg'ich", "Ruletka", "Tarozi"], correctIndex: 0 },
    { text: "Tikuv mashinasida matoni oldinga siljituvchi detal nima?", options: ["Tishli reyka", "Igna", "Moki", "G'altak"], correctIndex: 0 },
    { text: "Tabiiy tolalarga nimalar kiradi?", options: ["Paxta, jun, ipak", "Kapron, neylon", "Lavsan, poliester", "Plastmassa"], correctIndex: 0 },
    { text: "O'simlikdan olinadigan eng asosiy to'qimachilik tolasi nima?", options: ["Paxta", "Jun", "Ipak", "Sintetika"], correctIndex: 0 },
    { text: "Mehnat xavfsizligi qoidalariga rioya qilish nima uchun kerak?", options: ["Shikastlanishlarning oldini olish uchun", "Faqat o'qituvchi talabi uchun", "Ishni tezroq tugatish uchun", "Shart emas"], correctIndex: 0 },
    { text: "Pazandalikda sabzavotlarni to'g'rash uchun nima ishlatiladi?", options: ["Oshxona taxtakachi va pichoq", "Bolg'a", "Qaychi", "Shtangensirkul"], correctIndex: 0 },
    { text: "C vitamini ko'p bo'lgan mahsulotlarni toping.", options: ["Limon, na'matak, qorag'at", "Non, go'sht", "Yog', shakar", "Tuz"], correctIndex: 0 },
    { text: "Elektr asboblari bilan ishlashda qanday qo'lqop kiyish tavsiya etiladi?", options: ["Rezina (dielektrik)", "Matoli", "Temir", "Charm"], correctIndex: 0 },
    { text: "Dazmollash jarayonida xavfsizlik uchun nima qilish kerak?", options: ["Ish tugagach dazmolni darhol tarmoqdan uzish", "Dazmolni yoqiq qoldirish", "Suv sepmaslik", "Simidan tortish"], correctIndex: 0 },
    { text: "Loyiha ishi tayyorlashning birinchi bosqichi nima?", options: ["G'oyani tanlash va rejalashtirish", "Buyumni sotish", "Reklama qilish", "Baholash"], correctIndex: 0 },
    { text: "Chizma chizishda qalamning qattiqligi qanday belgilanadi?", options: ["H va B", "A va C", "X va Y", "P va S"], correctIndex: 0 }
  ],

  "Rus tili": [
    { text: "Сколько букв в русском алфавите?", options: ["33", "30", "32", "34"], correctIndex: 0 },
    { text: "Какое слово отвечает на вопрос \"Кто?\"?", options: ["Ученик", "Книга", "Парта", "Школа"], correctIndex: 0 },
    { text: "Какое слово отвечает на вопрос \"Что?\"?", options: ["Тетрадь", "Учитель", "Мальчик", "Собака"], correctIndex: 0 },
    { text: "Выберите слово женского рода:", options: ["Девочка", "Мальчик", "Стол", "Окно"], correctIndex: 0 },
    { text: "Выберите слово среднего рода:", options: ["Солнце", "Луна", "Звезда", "Дом"], correctIndex: 0 },
    { text: "Какое окончание имеет прилагательное в слове: \"Красив... школа\"?", options: ["-ая", "-ый", "-ое", "-ие"], correctIndex: 0 },
    { text: "Антоним к слову \"Большой\":", options: ["Маленький", "Огромный", "Высокий", "Длинный"], correctIndex: 0 },
    { text: "Синоним к слову \"Красивый\":", options: ["Прекрасный", "Ужасный", "Серый", "Грустный"], correctIndex: 0 },
    { text: "Множественное число слова \"Книга\":", options: ["Книги", "Книгов", "Книгам", "Книгах"], correctIndex: 0 },
    { text: "Выберите глагол:", options: ["Читать", "Чтение", "Книга", "Умный"], correctIndex: 0 },
    { text: "В каком времени стоит глагол \"Я написал\"?", options: ["Прошедшее время", "Настоящее время", "Будущее время", "Повелительное"], correctIndex: 0 },
    { text: "Сколько гласных букв в русском языке?", options: ["10", "6", "12", "8"], correctIndex: 0 },
    { text: "Какое местоимение 1-го лица единственного числа?", options: ["Я", "Ты", "Он", "Мы"], correctIndex: 0 },
    { text: "Как переводится \"Xayrli tong\" на русский язык?", options: ["Доброе утро", "Добрый день", "Добрый вечер", "Спокойной ночи"], correctIndex: 0 },
    { text: "Выберите правильный предлог: \"Я иду ... школу.\"", options: ["в", "на", "с", "из"], correctIndex: 0 }
  ]
};